### ISSUE TITLE
No such file or directory with lazy ember-engine

### ISSUE THREAD

**Issue by GCheung55** [kimroen/ember-cli-document-title#61]
I'm seeing the following error with a lazy in-repo-engine:

```
Error: ENOENT: no such file or directory, open '/someproject/tmp/source_map_concat-input_base_path-OKV17DZi.tmp/vendor/document-title/document-title.js'
```
The in-repo-engine has the `ember-cli-document-title` listed in the `package.json` dependency field.

**Comment by kimroen** [comment]
Thanks!

I don't know why this is, but my immediate thought it that it has something to do with this:

https://github.com/kimroen/ember-cli-document-title/blob/505367ef908a78e30e879687309fa53099ab9406/index.js#L8-L11

I see this fix has evolved quite a bit since we added that, as we can see in the similar code in `ember-font-awesome`:

https://github.com/martndemus/ember-font-awesome/blob/c5b6e63b200f6d4b62c83a20dd0c4018431aa1a2/index.js#L58-L73

I doubt I'll have the time to investigate this further any time soon unfortunately, so if anyone else wants to have a go at it then feel free to do so!

**Comment by GCheung55** [comment]
Going to close this. Doesn't seem like an issue anymore. I'll open a new one if it comes up again.
